# This is a basic workflow to help you get started with Actions

name: my_ferst.yml

# Controls when the workflow will run
on:
 push:
    branches:
        - master
        
jobs:
  my_test1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello world
      run : echo "Hello World from test job"
    
     

  my_deploy:
     runs-on: ubuntu-latest
     steps:
     - name: print Hello Message
       run : echo "Hello World from Deploy job"
